export const fonts = [
  "system-ui",
  "Abel",
  "Anton",
  "Cabin",
  "Caveat",
  "Dancing Script",
  "Fredoka One",
  "Lilita One",
  "Lobster",
  "Permanent Marker",
  "Play",
  "Rubik Vinyl",
  "Satisfy",
  "Shadows Into Light",
  "Archivo",
  "Boogaloo",
  "Cinzel",
  "Fira Sans",
  "Indie Flower",
  "JetBrains Mono",
  "Monoton",
  "Poppins",
  "Raleway",
  "Roboto Slab",
  "sans-serif",
];
