export const fonts = [
    "system-ui",
    "Abel",
    "Anton",
    "Cabin",
    "Caveat",
    "Dancing Script",
    "Fredoka One",
    "Lilita One",
    "Lobster",
    "Permanent Marker",
    "Play",
    "Press Start 2P",
    "Rubik 80s Fade",
    "Rubik Vinyl",
    "Satisfy",
    "Shadows Into Light",
    "sans-serif",
  ];